export { default as AltFavicon } from './alt-favicon.png'
export { default as AltFavicon2 } from './alt-favicon2.png'
export { default as Favicon } from './favicon.svg'
export { default as OGImage } from './og-image.png'
export { default as PinnedIcon } from './pinned-icon.svg'
export { default as TwitterCard } from './twitter-card.png'
